In [9]:
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [10]:
inp = np.array(([4,5,8,7],[1,8,8,8],[3,6,6,4],[6,5,7,8]))
print(inp.shape)
inp

(4, 4)


array([[4, 5, 8, 7],
       [1, 8, 8, 8],
       [3, 6, 6, 4],
       [6, 5, 7, 8]])

In [11]:
k=np.array(([1,4,1],[1,4,3],[3,3,1]))
print(k.shape)
k

(3, 3)


array([[1, 4, 1],
       [1, 4, 3],
       [3, 3, 1]])

In [12]:
w,h=inp.shape
w_k,h_k=k.shape
s =1
w_o=int(((w-w_k)/s)+1)
h_o=int(((h-h_k)/s)+1)
ext_mat =np.zeros(w*h)
print(ext_mat)
for i in range(w_k):
    ext_mat[i*h:i*h+h_k] =k[i]
print(ext_mat)
print(ext_mat.shape)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 4. 1. 0. 1. 4. 3. 0. 3. 3. 1. 0. 0. 0. 0. 0.]
(16,)


In [13]:
ext_ker = []
for i in range (w_o):
  for j in range (h_o):
    ext_mat1 = np.roll(ext_mat,h*i*s+j*s)
    ext_ker.append(ext_mat1)
ext_ker=np.array(ext_ker)
print("Convolution matrix")
print(ext_ker)
print(ext_ker.shape)



Convolution matrix
[[1. 4. 1. 0. 1. 4. 3. 0. 3. 3. 1. 0. 0. 0. 0. 0.]
 [0. 1. 4. 1. 0. 1. 4. 3. 0. 3. 3. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 4. 1. 0. 1. 4. 3. 0. 3. 3. 1. 0.]
 [0. 0. 0. 0. 0. 1. 4. 1. 0. 1. 4. 3. 0. 3. 3. 1.]]
(4, 16)


In [14]:
inp = inp.flatten()
print(inp)
out1 = np.matmul(ext_ker,inp)
print(out1)
out2 = np.reshape(out1,(w_o,h_o))
print(out2)
print(out2.shape)

[4 5 8 7 1 8 8 8 3 6 6 4 6 5 7 8]
[122. 148. 126. 134.]
[[122. 148.]
 [126. 134.]]
(2, 2)
